POST https://26yve06bzk.execute-api.us-east-1.amazonaws.com/Latest/Weather/Reading
Content-Type: application/json

{
  "stationId": "2"
}
###
POST https://26yve06bzk.execute-api.us-east-1.amazonaws.com/calculate/water
content-type: application/json

{
  "lat": 40.7128,
  "lon": -74.0060
}
###
POST https://26yve06bzk.execute-api.us-east-1.amazonaws.com/calculate/water
content-type: application/json

{
  "lat": 26.15,
  "lon": 50.5556
}

###
POST https://26yve06bzk.execute-api.us-east-1.amazonaws.com/Latest/Weather/Reading
content-type: application/json

{
  "pathParameters": 2
  //  "queryStringParameters": -74.0060
}


###
POST https://26yve06bzk.execute-api.us-east-1.amazonaws.com/Upload/CSV
content-type: application/json

{
"fileName": "test.csv",
"fileType": "csv"
}

###
PUT https://your-api-endpoint.com/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="yourfile.csv"
Content-Type: text/csv

@./path/to/yourfile.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--





###
GET  https://26yve06bzk.execute-api.us-east-1.amazonaws.com/crops

<> 2024-12-03T202405.200.txt
<> 2024-12-03T202142.200.txt



