/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/../../frontend/src/Components/crops/CropsTable`; params?: Router.UnknownInputParams; } | { pathname: `/../../frontend/src/App`; params?: Router.UnknownInputParams; } | { pathname: `/../../frontend/src/pages/AdminDashboard`; params?: Router.UnknownInputParams; } | { pathname: `/../../frontend/src/pages/Dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/../../frontend/src/pages/Farms`; params?: Router.UnknownInputParams; } | { pathname: `/../../frontend/src/pages/Crops`; params?: Router.UnknownInputParams; } | { pathname: `/../../frontend/src/pages/Reports`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownInputParams; } | { pathname: `/screens/AuthScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Crop`; params?: Router.UnknownInputParams; } | { pathname: `/screens/DashBoard`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Recommendation`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/../../frontend/src/Components/crops/CropsTable`; params?: Router.UnknownOutputParams; } | { pathname: `/../../frontend/src/App`; params?: Router.UnknownOutputParams; } | { pathname: `/../../frontend/src/pages/AdminDashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/../../frontend/src/pages/Dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/../../frontend/src/pages/Farms`; params?: Router.UnknownOutputParams; } | { pathname: `/../../frontend/src/pages/Crops`; params?: Router.UnknownOutputParams; } | { pathname: `/../../frontend/src/pages/Reports`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/AuthScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Crop`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/DashBoard`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Recommendation`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/../../frontend/src/Components/crops/CropsTable${`?${string}` | `#${string}` | ''}` | `/../../frontend/src/App${`?${string}` | `#${string}` | ''}` | `/../../frontend/src/pages/AdminDashboard${`?${string}` | `#${string}` | ''}` | `/../../frontend/src/pages/Dashboard${`?${string}` | `#${string}` | ''}` | `/../../frontend/src/pages/Farms${`?${string}` | `#${string}` | ''}` | `/../../frontend/src/pages/Crops${`?${string}` | `#${string}` | ''}` | `/../../frontend/src/pages/Reports${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/two${`?${string}` | `#${string}` | ''}` | `/two${`?${string}` | `#${string}` | ''}` | `/screens/AuthScreen${`?${string}` | `#${string}` | ''}` | `/screens/Crop${`?${string}` | `#${string}` | ''}` | `/screens/DashBoard${`?${string}` | `#${string}` | ''}` | `/screens/Recommendation${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/../../frontend/src/Components/crops/CropsTable`; params?: Router.UnknownInputParams; } | { pathname: `/../../frontend/src/App`; params?: Router.UnknownInputParams; } | { pathname: `/../../frontend/src/pages/AdminDashboard`; params?: Router.UnknownInputParams; } | { pathname: `/../../frontend/src/pages/Dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/../../frontend/src/pages/Farms`; params?: Router.UnknownInputParams; } | { pathname: `/../../frontend/src/pages/Crops`; params?: Router.UnknownInputParams; } | { pathname: `/../../frontend/src/pages/Reports`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownInputParams; } | { pathname: `/screens/AuthScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Crop`; params?: Router.UnknownInputParams; } | { pathname: `/screens/DashBoard`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Recommendation`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
